### ISSUE TITLE
Do some automated testing

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/structure-from-motion#24]
Jurriaan added a Python script that can help retrieve the number of points from the sparse point cloud and the dense point cloud. Could be useful as a crude quality measure in e2e testing.

https://github.com/NLeSC/PattyGenerate/blob/4f48e419418e67c3ff9b243e4b6f4e7ddce56458/number-of-points/number-of-points.py

**Comment by nielsdrost** [comment]
Added an explanation of using the script in the new example docs (docs/example.md).

**Comment by nielsdrost** [comment]
Sanity check written in #10, next step is to use in automated build

**Comment by nielsdrost** [comment]
pipeline now running in Travis (see badge in README).
