### ISSUE TITLE
pipeline doesn't support spaces in cwd path

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/structure-from-motion#34]
/media/christiaan/UUI/2017 mei pointcloud$ sudo docker run -u $UID -v $PWD:/data nlesc/structure-from-motion
[sudo] password for christiaan: 
Unable to find image 'mei:latest' locally
docker: Error response from daemon: repository mei not found: does not exist or no pull access.
See 'docker run --help'.

**Comment by nielsdrost** [comment]
The command does not seem to get to the pipeline at all. The $PWD expands into your path, misleading the docker command into thinking the name of your image is "mei" Perhaps surround the PWD with quotes?:

    sudo docker run -u $UID -v "$PWD:/data" nlesc/structure-from-motion

**Comment by nielsdrost** [comment]
Also: thanks for reporting this :-)

**Comment by cwmeijer** [comment]
That works of course. I just copied and pasted from documentation without thinking :-) 
Created pull request for docker documentation.
